backend:
  name: github
  repo: delphiorg/delphiorg.github.io
  branch: main
  base_url: https://decap-proxy.jim-557.workers.dev
  auth_endpoint: /auth

publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Jim McKeeth", required: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - { label: "Body", name: "body", widget: "markdown" }
